language: c
branches:
  only:
  - master
os:
- linux
- osx
script:
- ./travis/build.sh
after_success:
- ./travis/upload.sh
env:
  global:
  - secure: jMT14+3HGSUnGIHvhKZ9VMBvaiFAu6onBqsBall1d8D+NyIK39KqsJCmyKFBBiFIgFgUJNeR8BTHQB/Dn3xCunotu/Ske2vTVngybRyA3UJNqjnU6nyr5slOvkpTmDyJNZw3ChDsTLrLLK33m8D/QRAQiOQhPEIEzgcK6gjaPn1XnrFoOEGURjucdD49FYDD8TsLLlzgijEHBWVgQBmovul2cC+euJAaFdmHlwER8cY/So4fPWpLdxcSSHeRj+TV6yqztfGFoUQh7Q4pJt45R/yAJX956Y+V26UWYljw5NULxXBrVRr0OmpsNqtPWWHqE3tJfEotdgKaetndTv3BYw//0TjVbr9/3YIIoovpT7dUuWYbtiwQypahID3Czj1QW3XxM/tOvOmfIgFrEhPNy+2Gw6Qz2pNGKrcyQib0jLMkfNTlvpyovb03IqHS8t+Nyz1oAzm2yhMew/seV1Pt6mHVEQ7Kuyqx+Mr23wuU+RnzAJqzYfiZkROXtPmau/ocd6XSIw53rGzvnBqo+K51ijXBw9cJGAgbdrxkd1RB8wSyd7GeL9SnYG/ZnrWWnSNU1R0MbHPdF/JJJQ/e6qaQjgHSAHK/GjXUG3mtnQop0wlBEtBXJc6N/3b8I969COJZ1+2WJNByr9ZOJZ931p6/zV5sy+7re2CYlmy6/OiYNh8=
  - secure: l/qjQ9lpFbipSZ1F4ZvGHXVaaTwfg4acP7rIrRxYXo/pJmSw8nboyJz2GsNf5I1lYAQDlBDdWRbkb+TA7+MneQRaEWLraIicwFIjJSyEjDGZngSbc8F694P4/MAAGgBK3OX1nJMFWBf8p6dl0xphvdcZutdkopRhA8Uzn++kHm/GNpQ5tk+vsgt4MZWxcwHxPuxskCH+N1VWaO/tZLSHjsBAwDH24z/S4N6ukkb7kDJYK6T7hpRI1LtCnomwHg7Lj8B5m9Ses7/aoHYNWiiY3nyl4+tdwoqedqye/lq5PSgH3+qSDKmaWGYhDhO7SuSFbUTeFCRRYM4kWLzSORF0Y61wABs8ydpWgR0cwONs6daYGGgZCG/rbH0yx/fdSRCNoRHXwwmmkQTmZl1mSFzQscd1GUDeBQn7yculh27HiOr9vUFCrQhJmY2gHV9TF0Hd0VpHBdJdUOjnOO3hJF4qX0H1ibWgUrxnv2OhSM2IrNuS+duqDXG9dhlnM9jkggdv+nxSOzn5bt9Pg8RDw1ZpBmz7KOVE8rFcrw7SW0PRdZGDOvl8+toiyGkkAoX9JG+OxXd40wapLlc6dyrANUTPe9h8ZPWhpvN61ymgj9h7EqLkOOOHe0Kv4PUdCu+xBKMvurk8y9iAaNbbEj3pbcTKTvwGwRqaA0JXWDj8xbvMbFE=
