language: c
branches:
  only:
  - master
os:
- linux
- osx
script:
- ./travis/build.sh
after_success:
- ./travis/upload.sh
env:
  global:
    secure: FufoIT63W3Kn0DD1YkI65E/yIfRBSJ50NBcdYgrXHwBwN7QgW+roWFCNoym1IbDlHUuWAJQ7XVrBbH/wIMdr4nPn4f5I81FuZAnxs6EEgbdy3kaILUu5Mf4zBqMO1D7A/V3hXW6+DnKiwfC5iiIbvWpm0DbQmhWeGS0LD8xrMjbC4QtYKyNQSGCS9G8tFYPA666nAEFcOKIV5eiB0z1FZmjpn2lxUKgjZXMQjhzsy2O+SX+84ILOQLCB9V0YWTfhne2BnAeco1wZg/kU2SmJI9BQfUm4PxLRpiBdVH6WhSngsdH1RErsvMFkbajA/d1ktUDjcRXJiCDlp3eefmntZiCN/M+UNplfAsc+6lVbPhqJoaynvyJLSRr5EnKXToPR2TK1rm76P2oTpYZk4aFYt80yXXHmXKs9M81WPW0Qhu1ZjMwnCoDmvgQrbYB9QdKxWUT8SxiYXwO81fpM+AZre/jYXPG70NHtiFkQ7FWOuDAxPfD/kGd6ZnoNiBWp+j4tVAnNYZzojZHn9FQ3evvZ/ueqxNZQnTfMP8EBzMsJXYIqMrnGbjVnsddUlfGuvH3EMVnsPG0wNMXqambVVQICyZ7l84njle9PTwSW8IvNIcaM0WVYsvmBofPo5ttgGrBZUPVWf+ru0yAuMEamy5/n3BEzUuiJNvAPuQ2MJtzEbOM=
