language: c

env:
  global:
	- GH_REF: github.com/carlosanunes/deadbeef_vfs_archive_reader
	- secure: "p5lRPAxYPtuWX526CDfIL9u6QVjS5XXGzvV8iXB2oFcJkp6v1sDVyNRQn8/f3HZoaIK+Rpnk/0CxDTq1OaOltAuZFatZe2zxUM34RmWUHAdx+PQaY5ik3QaFLCmVDtKw95wq0EWAmOyneNwuM4Br9+wqZQardpERrCS/smyceIj5tjC1bOIydptvs8QijKJfi19w4Huhq5kARpR69fWIiUM26zBFiBHJDvh/PPTJmGoffgFzG9zkmn0TbsjZSIOIEMk0Qhgk5zkiPOVctRs462Zd3xnBADuA1HG48pA/cfs4vqGzmaHdNXhxT2DsfxpPan681EA7x6yiuNh1hBqYR3FgMbVqIXjC/Dyux6nqalsuSjhQWBltlnvH971xt+wM+kqs30av7E/r+ed5KcrrogOcXCGU7kbCsbKQZRJHtLd0RIHQRpvvWiorQLW+k5HO0bn94vfDRBHECNW+dS15thR6orM3RKCwGmnk3WC/ZcQ0M8iOOgod12Xm/2dZkyqmmiBh4Orj/+r4I7E5LrbRo73tv0+pt1NJ5jTdAKF2qSJST8LvT0BQRBGBfgr94SYB1tW9+XlotAGzgY5Qgnn44iD1i2mHxXfD3BfOkaiGyjqh9gt07qjzTBlo1/OggoFSLmYZfm1rby2mqMVtiTj1Ogw2VkiFDHeTMXWmJpwNVXI="

branches:
    only:
    - master

os:
    - linux
    - osx

script:
    - ./travis/build.sh

after_success:
    - ./travis/upload.sh
